language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - cp ../ZfrForum/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - rm -rf vendor/zfr/zfr-forum
  - cp -r ../ZfrForum vendor/zfr/zfr-forum
  - rm config/application.config.php && cp ../ZfrForum/.travis/application.config.php config/

script:
  - cd vendor/zfr/zfr-forum/tests
  - phpunit
